openshift/cluster-api-provider-agent

- Makefile
- config/default/kustomization.yaml
Allow specifying the namespace when deploying from source code
> Remove the 'system' suffix from the capi-provider-agent default namespace

- controllers/agentmachine_controller.go
All agents belonging to the same node pool use the same ignitionTokenSecret.
The provider assumed the token never changes but it seems that HyperShift updates the token inside the userDataSecret, hence the provider should update the ignitionTokenSecret as well.
> Mgmt 8764: agent fail to pull ignition due to expired token

- main.go
In case that the provider is deployed on a specific namespace with
limited RBAC, the provider needs to specify on which namespace the
controllers will be watching.
> MGMT-8821: Option to specify watch namespace

- controllers/agentmachine_controller.go
- controllers/agentmachine_controller_test.go
- main.go
Add a additional controller manager to handle cache of Agents on a different namespace than the CAPI objects.
> MGMT-8819:  List agents by namespace

- Makefile
This commit adds RUNTIME variable to Makefile so that developer can
configure a desired CLI for building and pushing images. The default
value is `docker` so that the behaviour is not modified but allows to
easily plug podman.
/cc @avishayt
> Update Makefile to allow setting runtime CLI

- config/default/manager_auth_proxy_patch.yaml
BZ2047937: Stops manager from crashing when using `make deploy` with `WATCH_NAMESPACE capi-0 AGENTS_NAMESPACE=capi-0-workers` arguments.
> BZ2047937: Fix Make deploy manager arguments

- controllers/agentcluster_controller.go
- controllers/agentcluster_controller_test.go
- controllers/agentmachine_controller.go
[MGMT-9278](https://issues.redhat.com/browse/MGMT-9278): Adding wait for control plane to be ready
and cleanup external watcher
> MGMT-9278: Adding wait for control plane to be ready

- controllers/agentcluster_controller.go
- controllers/agentcluster_controller_test.go
Currently, when running with HIVE the cluster_controller fails to create the ClusterDeploymeent due to:
```
"error": "admission webhook \"ocm.validating.webhook.admission.open-cluster-management.io\" denied the request: user \"system:serviceaccount:clusters-hdhcp-0:capi-provider\" cannot add/remove the resource to/from ManagedClusterSet 
```
Adding the OwnerRef should enable ACM to skip this webhook (they do a similar trick for clusterclaim)
> MGMT-9390: Add owner ref on the ClusterDeployment

- controllers/agentcluster_controller.go
- controllers/agentcluster_controller_test.go
This should allow the assisted-service to approve the node (and kubelet) CSRs
> Set user maneged networking to true in the agentCluster agentClusterInstall

- OWNERS
Since there are (currently) no label restrictions on attached Jira bugs, we don't have a good way to enforce people are only merging bug-fixes / security-patches.
Setting a smaller approvers list can help us enforce this kind of restriction (list might change later on, if needed)
/cc @filanov @gamli75 @romfreiman @eranco74
> MGMT-12840: set restricted list of approvers for 2.7

- controllers/agentmachine_controller.go
- controllers/agentmachine_controller_test.go
In e6fa01e the machine pre-delete hook replaced this finalizer, but it now seems that there are scenarios where the `AgentMachine` could be deleted before the `Machine`. Before this change this would mean that the pre-delete hook would never get removed from the `Machine`, stalling the delete process indefinitely.
Now this finalizer will prevent `AgentMachines` from being removed before the pre-delete work is processed for the `Machine`. The annotation is added and removed at the same time as the pre-delete hook.
Resolves https://issues.redhat.com/browse/ACM-2433
> Add back the agent machine finalizer

- controllers/agentmachine_controller.go
- controllers/agentmachine_controller_test.go
We modify an agent when associating it with an agentMachine, but failed to undo those changes upon disassociating it. This commit fixes that.
> ACM-3757: Undo changes to agents upon unbinding

- Dockerfile
https://issues.redhat.com/browse/MGMT-15235
In order to be FIPS compliant, we need to compile
all go code with CGO_ENABLED=1.
/cc @eranco74 @filanov
> MGMT-15235: Compile with CGO_ENABLED=1 for FIPS

- controllers/agentcluster_controller.go
- controllers/agentmachine_controller.go
- controllers/common.go
- controllers/common_test.go
- controllers/remote_client.go
https://issues.redhat.com/browse/MGMT-9661
Epic: https://issues.redhat.com/browse/MGMT-10606
Adds backup label `cluster.open-cluster-management.io/backup: true` to secrets required by CAPI.
Labels the following secrets:
AgentMachine: IgnitionTokenSecret, bootstrapDataSecret AgentCluster: ignitionEndpoint's CA Certificate, control plane's pull secret, control plane's kubeconfig secret, control plane's kubeadmin password secret
RemoteClient: admin-kubeconfig secret
/cc @filanov @eranco74
> MGMT-9661: Label CAPI secrets for backup

- go.mod
- go.sum
- vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
- vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
- vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
- vendor/github.com/openshift/api/config/v1/0000_10_openshift-controller-manager-operator_01_build.crd.yaml
- vendor/github.com/openshift/api/config/v1/feature_gates.go
- vendor/github.com/openshift/api/config/v1/stable.build.testsuite.yaml
- vendor/github.com/openshift/api/config/v1/stable.clusterversion.testsuite.yaml
- vendor/github.com/openshift/api/config/v1/types_cluster_version.go
- vendor/github.com/openshift/api/config/v1/types_feature.go
- vendor/github.com/openshift/api/config/v1/types_image.go
- vendor/github.com/openshift/api/config/v1/types_infrastructure.go
- vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
- vendor/github.com/openshift/cluster-api-provider-agent/api/v1alpha1/agentcluster_types.go
- vendor/github.com/openshift/cluster-api-provider-agent/api/v1alpha1/agentmachine_types.go
- vendor/github.com/openshift/cluster-api-provider-agent/api/v1alpha1/agentmachinetemplate_types.go
- vendor/github.com/openshift/cluster-api-provider-agent/api/v1alpha1/conversion.go
- vendor/github.com/openshift/cluster-api-provider-agent/api/v1alpha1/groupversion_info.go
- vendor/modules.txt
Missed updating the vendor directory in https://github.com/openshift/cluster-api-provider-agent/pull/89
/cc @filanov
> [release-ocm-2.9] MGMT-14838: Update vendor directory after backporting v1beta1 changes

- controllers/agentmachine_controller.go
The call to Update was replaced by ensureSecretLabel in commit 83908f2e80bc. This introduces a bug because ensureSecretLabel calls Update only if a label doesn't already exist, whereas we need to call it every time.
> ACM-8593: Update ignition token on refresh

- controllers/agentmachine_controller.go
- controllers/agentmachine_controller_test.go
- main.go
https://issues.redhat.com/browse/OCPBUGS-24922
To prevent the AgentMachine from retrieving a cached Agent (resulting in stale data).
/cc @avishayt
> OCPBUGS-24922: Retrieve Agent object directly

- OWNERS
Add cloud team in order to ease maintenance operations on this repo like
ocm branch cut-off.
> NO-ISSUE: Add cloud team to the OWNERS

- Dockerfile
- go.mod
This PR
- Bumps golang version to 1.20 (as some dependencies require)
- Replaces golang base image to UBI (as CI golang base image is based on Centos Linux 7)
> MGMT-18313: Replace golang base image as it is based on Centos Linux 7

- Dockerfile
- Makefile
- go.mod
This PR
- Bumps golang version to 1.20 (as some dependencies require)
- Replaces golang base image to UBI (as CI golang base image is based on Centos Linux 7)
> [release-ocm-2.9] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

- Dockerfile
- go.mod
This PR
- Bumps golang version to 1.20 (as some dependencies require)
- Replaces golang base image to UBI (as CI golang base image is based on Centos Linux 7)
> [release-ocm-2.10] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

- controllers/agentmachine_controller.go
- controllers/agentmachine_controller_test.go
Originally, the condition to not unbind the Agent
was based on if the AgentMachine is paused AND if the AgentMachine had a deletionTimestamp. This caused
the Agent to be unbound when the deletionTimestamp didn't exist yet on the AgentMachine, and is flawed logic.
This change updates the condition to make sure we
don't continue to unbind the Agent if the AgentMachine is at all paused.
/cc @carbonin
> OCPBUGS-32592: Ensure Agent isn't unbound if paused

- controllers/remote_client.go
Currently we add schemes to the remote client with every call to the `GetRemoteClient` method. But this is called during reconciliation, when there may be other things trying to read those schemes. That can potentially cause a concurrent map read and map write. To reduce the chances of that happening this patch changes the code so that the schemes will be added only when the remote client is created, which happens only once.
Related: https://issues.redhat.com/browse/MGMT-18689
> MGMT-18689: Add schemes when remote client is created

- controllers/remote_client.go
This is a backport of MGMT-18689 and #149 to ACM 2.12.
Currently we add schemes to the remote client with every call to the `GetRemoteClient` method. But this is called during reconciliation, when there may be other things trying to read those schemes. That can potentially cause a concurrent map read and map write. To reduce the chances of that happening this patch changes the code so that the schemes will be added only when the remote client is created, which happens only once.
Related: https://issues.redhat.com/browse/MGMT-19137
Related: https://issues.redhat.com/browse/MGMT-18689
> [ACM 2.12] MGMT-19137: Add schemes when remote client is created

- Dockerfile
Currently, in most of assisted installer components CI images we don't have a way to tell from which commit reference the image was built. Since We use an image stream for each component, and we import these streams from one CI component configuration to another, we might end up with images to are not up-to-date. In this case, we would like to have the ability to check if this is actually the case.
> MGMT-19819: Add the commit reference from which the image is built to the image

- config/crd/bases/capi-provider.agent-install.openshift.io_agentmachines.yaml
- controllers/agentmachine_controller.go
- controllers/agentmachine_controller_test.go
Previously when selecting an Agent for the AgentMachine, there were no checks for whether or not the Agent was still connected. This is a problem if an Agent becomes disconnected and the controller selects it to be installed into the hosted cluster since the Agent cannot be contacted.
This modifies the valid agent function so that an Agent is valid only if it meets the following criteria:
1. It is not already bound to a ClusterDeployment
2. It is connected
3. It is approved
4. Its validations are passing
> MGMT-19762: Don't use a disconnected Agent

- controllers/agentmachine_controller.go
- controllers/agentmachine_controller_test.go
When the AgentMachine's finalizer is removed, the deletionTimestamp is also removed.
Previously, anytime the finalizer is successfully removed, we allow the reconciliation to continue, which is problematic since the AgentMachine will have no indication that it is actually being deleted. 
This leads to problems like when scaling down a NodePool, the AgentMachine controller will unbind the Agents, but then re-add the AgentMachineRef label to those Agents later on in the reconcile logic. The Agents will then not be able to be bound again unless the AgentMachineRef label is removed manually.
This change ensures that whenever the AgentMachine has successfully had its finalizer removed that we end the reconciliation cycle.
> NO-ISSUE: Prevent further reconciling after removing AgentMachine finalizer

- .tekton/cluster-api-provider-agent-mce-29-pull-request.yaml
This is an empty commit to trigger a Konflux build.
The init task image reference updated to fix the enterprise contract violation.
> Trigger konflux build

- Dockerfile.rhtap
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
> chore(KONFLUX-6210): fix and set name and cpe label for cluster-api-provider-agent-mce-29

- renovate.json
Since we've added tekton files to every `release-ocm-xxx` branch, renovate will open PRs to update dependencies on those branches too. This is unnecessary as they are maintained release branches for ACM, but they do not need dependency upgrades.
> NO-ISSUE: Update renovate to only update dependencies for master branch
