controllers/agentmachine_controller.go, controllers/agentmachine_controller_test.go
=> Added RequeueAfter 30 seconds in case there is no available Agent for the AgentMachine

Makefile, README.md, config/default/manager_auth_proxy_patch.yaml, docs/namespaced-operator-permissions.md
Update makefile targets and documentation with the namespace scope options
=> Add namespace scope options

controllers/agentmachine_controller.go, controllers/agentmachine_controller_test.go
To allow multiple instances of the provider to run simultaneously, we
now:
1. Update the Agent in one call, including a label referencing the
AgentMachine.
2. Update the AgentMachine in one call.
3. If we did step 1 but failed on step2, use the label on the Agent to
skip to step 2.
=> MGMT-8849: Avoid races when matching agents

controllers/agentcluster_controller.go
In case the controller created the clusterDeployment and failed to update the agentCluster
on every subsequent reconciliation, the controller will try to create the ClusterDeployment and fail because it exists.
=> MGMT-9254 Failure to update agentCluster.Status breaks reconciliation

controllers/agentcluster_controller.go, controllers/agentcluster_controller_test.go
Bug 2045067: Adding clustermetadata to clusterdeployment
=> MGMTBUGSM-76:Adding clustermetadata to clusterdeployment

controllers/agentcluster_controller.go
Create the ACI with ProvisionRequirements
Requeue in case ACI doesn't exists and need to be created
=> MGMT-9255 agentcluster_controller sometimes fails to update the ACI

api/v1alpha1/agentmachine_types.go, controllers/agentmachine_controller.go, controllers/agentmachine_controller_test.go, vendor/github.com/openshift/cluster-api-provider-agent/api/v1alpha1/agentmachine_types.go, vendor/modules.txt, vendor/sigs.k8s.io/cluster-api/util/conditions/doc.go, vendor/sigs.k8s.io/cluster-api/util/conditions/getter.go, vendor/sigs.k8s.io/cluster-api/util/conditions/matcher.go, vendor/sigs.k8s.io/cluster-api/util/conditions/matchers.go, vendor/sigs.k8s.io/cluster-api/util/conditions/merge.go, vendor/sigs.k8s.io/cluster-api/util/conditions/merge_strategies.go, vendor/sigs.k8s.io/cluster-api/util/conditions/patch.go, vendor/sigs.k8s.io/cluster-api/util/conditions/setter.go, vendor/sigs.k8s.io/cluster-api/util/conditions/unstructured.go
Create conditions for finding an agent and installing the node, and
implement the Ready Condition which is bubbled up to the nodepool.
Status when no agents available:
```
conditions:
- lastTransitionTime: "2022-03-31T10:17:31Z"
message: 0 of 5 completed
reason: NoSuitableAgentFound
severity: Warning
status: "False"
type: Ready
- lastTransitionTime: "2022-03-31T10:17:31Z"
message: Agent not yet reserved
reason: AgentNotYetFound
severity: Info
status: "False"
type: AgentRequirementsMet
- lastTransitionTime: "2022-03-31T10:17:31Z"
reason: NoSuitableAgentFound
severity: Warning
status: "False"
type: AgentReserved
- lastTransitionTime: "2022-03-31T10:17:31Z"
message: Agent not yet reserved
reason: AgentNotYetFound
severity: Info
status: "False"
type: AgentSpecSynced
- lastTransitionTime: …
```
=> MGMT-9821: Add Conditions to AgentMachines

README.md
Just some typos in the README file.
/cc @eranco74
=> NO-ISSUE: fixing some typos in the README

controllers/agentcluster_controller.go
The e2e test is broken for some time now, this should get it passing again until we sort out the issue with the missing kubeadmin password
/hold
=> In case the hostedcontrolplane doesn't have the kubeadminPassword, create the clusterDeployment without it

controllers/agentcluster_controller.go
The `AgentClusterInstall` webhook prevents setting the ignition endpoint after the initial create.  The only code path for setting the ignition endpoint sets it after create which does not work.
https://github.com/openshift/cluster-api-provider-agent/blob/22297e732a690fce2485f723b4da9aed99f1bab1/controllers/agentcluster_controller.go#L118-L147
```
1.655390335604201e+09	ERROR	controller.agentcluster	Reconciler error	{"reconciler group": "capi-provider.agent-install.openshift.io", "reconciler kind": "AgentCluster", "name": "sjenning-example", "namespace": "clusters-sjenning-example", "error": "admission webhook \"agentclusterinstallvalidators.admission.agentinstall.openshift.io\" denied the request: Attempted to change AgentClusterInstall.Spec which is immutable after install started, …
```
=> Set ignition endpoint at AgentClusterInstall creation

controllers/agentmachine_controller.go, controllers/agentmachine_controller_test.go
In e6fa01e the machine pre-delete hook replaced this finalizer, but it now seems that there are scenarios where the `AgentMachine` could be deleted before the `Machine`. Before this change this would mean that the pre-delete hook would never get removed from the `Machine`, stalling the delete process indefinitely.
Now this finalizer will prevent `AgentMachines` from being removed before the pre-delete work is processed for the `Machine`. The annotation is added and removed at the same time as the pre-delete hook.
Resolves https://issues.redhat.com/browse/ACM-2841
Backports #62
=> Add back the agent machine finalizer

controllers/agentmachine_controller.go, controllers/node_provider_id_controller.go, controllers/node_provider_id_controller_test.go
Use fieldSelector instead of filtering in a loop
update few logs
=> Improve AgentToAgentMachine mapping

controllers/agentmachine_controller.go
Filter Agent in the loop instead of fieldSelector due to: "non-exact field matches are not supported by the cache" error
=> MGMT-14607 Machine stuck in pending state in agent cluster

OWNERS
=> NO-ISSUE: Add Michael as an approver

controllers/agentmachine_controller.go, controllers/agentmachine_controller_test.go
AgentMachines need to be reconciled if they don't yet have an Agent, and and a valid Agent is modified. Otherwise AgentMachines that don't yet have an Agent will not be reconciled when an Agent becomes available.
=> OCPBUGS-25599: Reconcile AgentMachines for unbound Agents

OWNERS
=> MGMT-17308: Offboard osherdp from maintainers list

controllers/agentcluster_controller.go, controllers/agentmachine_controller.go
=> NO-ISSUE: Ignore not found error when finding ClusterDeployment

controllers/agentcluster_controller_test.go
While updating the dependencies of the project I noticed that these two tests started to fail because the agent cluster object doesn't have the `apiVersion` and `kind` fields populated, and that is used by the new versions of the functions that compare owner references. But when I fixed that the test started to fail because the setup of the agent cluster isn't correct for the test: it needs to have a valid `status.clusterDeploymentRef` and a valid `spec.controlPlaneEndpoint`, otherwise the reconciler will not do the orphaning logic, or will reject the object completely. This patch fixes those tests so that they work now and will also work when updated to newer versions of the dependencies.
=> NO-ISSUE: Fix agent cluster controller orphaning tests

controllers/agentmachine_controller.go, controllers/agentmachine_controller_test.go
The secret used as the bearer token for the ignition server should always be updated or created regardless of the status of the AgentMachine. This is to prevent scenarios where the secret is deleted but not recreated when an AgentMachine is ready.
=> MGMT-19496: Always reconcile ignition token secret

controllers/agentmachine_controller.go, controllers/agentmachine_controller_test.go
Reverts openshift/cluster-api-provider-agent#161 (which was a revert PR itself) now that ACM 2.11.5 has GA'd. 
The original revert intended to remove the only change in ACM 2.11's branch for the ACM 2.11.5 release due to the request that the ACM 2.11.5 release be a CVE-only release. 
/cc @gamli75
=> Revert prior "Revert "[release-ocm-2.11] MGMT-19496: Always reconcile ignition token secret""

OWNERS
=> [release-ocm-2.13] NO-ISSUE: Remove eran ifrach account from OWNERS

OWNERS
=> NO-ISSUE: Remove eran ifrach account from OWNERS

.tekton/cluster-api-provider-agent-mce-29-pull-request.yaml, Dockerfile.rhtap
Updated the konflux Dockerfile to fix multi arch image builds.
=> Konflux multi-arch fix

.tekton/cluster-api-provider-agent-mce-29-pull-request.yaml, .tekton/cluster-api-provider-agent-mce-29-push.yaml
https://issues.redhat.com/browse/ACM-23668
=> Fixing EC violations 
